### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: "sharpen.page: A Product Sharpening Service"
email: pascal@pascallaliberte.me
description: "I help modest online products and service businesses (like your freelancing practice) going through situations like these…"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://sharpen.page # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#605aa4'
twitter_username: pascallaliberte
github_username:  pascallaliberte
author: Pascal Laliberté
twitter:
  username: pascallaliberte
social:
  name: Pascal Laliberté
  links:
    - https://twitter.com/pascallaliberte
    - https://github.com/pascallaliberte

defaults:
  - scope:
      path: ""
    values:
      image: 
        path: /assets/images/a-product-sharpening-service.jpg
        height: 400
        width: 400

permalink: /:categories/:title/

ampdir: amp
destination: public

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _redirects

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
